apiVersion: apps/v1
kind: Deployment
metadata:
  name: city-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: city-app
  template:
    metadata:
      labels:
        app: city-app
    spec:
      containers:
        - name: city-app
          image: <image-name>:<image-tag>  # Replace with the Docker image details
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: city-app
spec:
  selector:
    app: city-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000